In [111]:
# ================================================================================
#                               MEDICAL ANALYASYS
# ================================================================================

In [112]:
# ---------------------------------------------
#             Data Cleaning
# ---------------------------------------------

In [113]:
# cleaning discharge table

In [114]:
import pandas as pd
import numpy as np

In [115]:
diabaties = pd.read_csv(r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\01_Raw_data\Diabitites.csv")
discharge = pd.read_excel(r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\01_Raw_data\Discharge.xlsx")
admission = pd.read_csv(r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\01_Raw_data\Admission.csv")
admission_source = pd.read_excel(r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\01_Raw_data\Addmision_Source.xlsx")

In [116]:
discharge

,discharge_disposition_id,description
0,1,Discharged to home
1,2,Discharged/transferred to another short term hospital
2,3,Discharged/transferred to SNF
3,4,Discharged/transferred to ICF
4,5,Discharged/transferred to another type of inpatient care institution
5,6,Discharged/transferred to home with home health service
6,7,Left AMA
7,8,Discharged/transferred to home under care of Home IV provider
8,9,Admitted as an inpatient to this hospital
9,10,Neonate discharged to another hospital for neonatal aftercare


In [117]:
discharge = discharge.iloc[0:0]

In [118]:
# Category	                    IDs Included
# Home	                        1, 6, 8
# Hospital Transfer         	2, 5, 23, 27, 29, 30
# Nursing/Rehab Care	        3, 4, 22, 24
# Hospice Care	                13, 14
# Expired	                    11, 19, 20, 21
# Outpatient Services	        12, 16, 17
# Psychiatric Care	            28
# Left Against Advice	        7
# Other/Unknown	                18, 25, 26
# Inpatient Admission	        9
# Neonatal Care	                10
# Swing Bed	                    15

In [119]:
discharge["discharge_disposition_id"] = range(1,13)

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\3123383783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  discharge["discharge_disposition_id"] = range(1,13)


In [120]:
discharge

,discharge_disposition_id,description
0,1,NaN
1,2,NaN
2,3,NaN
3,4,NaN
4,5,NaN
5,6,NaN
6,7,NaN
7,8,NaN
8,9,NaN
9,10,NaN


In [121]:
discharge.loc[
    discharge["discharge_disposition_id"] == 1,
    "description"
] = "Home"

In [122]:
description_map = {
    1: "Home",
    2: "Hospital Transfer",
    3: "Nursing/Rehab Care",
    4: "Hospice Care",
    5: "Expired",
    6: "Outpatient Services",
    7: "Psychiatric Care",
    8: "Left Against Advice",
    9: "Inpatient Admission",
    10: "Neonatal Care",
    11: "Swing Bed",
    12: "Outpatient Return"
}

In [123]:
# Category	                IDs Included
# Home	                    1, 6, 8
# Hospital Transfer	        2, 5, 23, 27, 29, 30
# Nursing/Rehab Care	    3, 4, 22, 24
# Hospice Care            	13, 14
# Expired	                11, 19, 20, 21
# Outpatient Services	    12, 16, 17
# Psychiatric Care	        28
# Left Against Advice     	7
# Other/Unknown	            18, 25, 26
# Inpatient Admission	    9
# Neonatal Care	            10
# Swing Bed	                15

In [124]:
discharge["description"] = discharge["discharge_disposition_id"].map(description_map)

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\3119857338.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  discharge["description"] = discharge["discharge_disposition_id"].map(description_map)


In [125]:
discharge

,discharge_disposition_id,description
0,1,Home
1,2,Hospital Transfer
2,3,Nursing/Rehab Care
3,4,Hospice Care
4,5,Expired
5,6,Outpatient Services
6,7,Psychiatric Care
7,8,Left Against Advice
8,9,Inpatient Admission
9,10,Neonatal Care


In [126]:

discharge.loc[len(discharge)] = [13, 'Unknown']

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\2357421682.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  discharge.loc[len(discharge)] = [13, 'Unknown']


In [127]:
discharge.dtypes

discharge_disposition_id     int64
description                 object
dtype: object

In [128]:
discharge["description"] = discharge["description"].astype("string")

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\1084519217.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  discharge["description"] = discharge["description"].astype("string")


In [129]:
discharge.dtypes

discharge_disposition_id             int64
description                 string[python]
dtype: object

In [130]:
# Category	IDs Included
# Home	1, 6, 8
# Hospital Transfer	2, 5, 23, 27, 29, 30
# Nursing/Rehab Care	3, 4, 22, 24
# Hospice Care	13, 14
# Expired	11, 19, 20, 21
# Outpatient Services	12, 16, 17
# Psychiatric Care	28
# Left Against Advice	7
# Other/Unknown	18, 25, 26
# Inpatient Admission	9
# Neonatal Care	10
# Swing Bed	15

In [131]:
discharge.to_csv(
    r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\02_Cleaned_data\cleaned_discharge_table.csv",
    index=False
)

In [132]:
# -----------------------------------------------------------------------------------------------------------------------------------------------

In [133]:
# cleaning admission table

In [134]:
admission

,admission_type_id,description
0,1,Emergency
1,2,Urgent
2,3,Elective
3,4,Newborn
4,5,Not Available
5,6,NaN
6,7,Trauma Center
7,8,Not Mapped


In [135]:
admission["description"] = admission["description"].fillna("Unknown")

In [136]:
admission.loc[
    admission["admission_type_id"].isin([5,6,8]),
    "admission_type_id"
] = 5

In [137]:
admission

,admission_type_id,description
0,1,Emergency
1,2,Urgent
2,3,Elective
3,4,Newborn
4,5,Not Available
5,5,Unknown
6,7,Trauma Center
7,5,Not Mapped


In [138]:
admission.loc[
    admission["admission_type_id"].isin([5]),
    "description"
] = "Unknown"

In [139]:
admission

,admission_type_id,description
0,1,Emergency
1,2,Urgent
2,3,Elective
3,4,Newborn
4,5,Unknown
5,5,Unknown
6,7,Trauma Center
7,5,Unknown


In [140]:
admission.dtypes 

admission_type_id     int64
description          object
dtype: object

In [141]:
admission['description'] = admission["description"].astype("string")

In [142]:
# -----------------------------------------------------------------------------------------------------------------------------------------------------

In [143]:
# cleaning admmission source table

In [144]:
admission_source

,admission_source_id,description
0,1,Physician Referral
1,2,Clinic Referral
2,3,HMO Referral
3,4,Transfer from a hospital
4,5,Transfer from a Skilled Nursing Facility (SNF)
5,6,Transfer from another health care facility
6,7,Emergency Room
7,8,Court/Law Enforcement
8,9,Not Available
9,10,Transfer from critial access hospital


In [145]:
admission_source = admission_source.iloc[0:0]
admission_source

,admission_source_id,description


In [146]:
admission_source["admission_source_id"] = range(1,23)

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\2314187864.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission_source["admission_source_id"] = range(1,23)


In [147]:
admission_source_map = {
    1: "Physician Referral",
    2: "Clinic Referral",
    3: "HMO Referral",
    4: "Hospital Transfer",
    5: "SNF Transfer",
    6: "Healthcare Transfer",
    7: "Emergency Room",
    8: "Law Enforcement",
    9: "Critical Hospital Transfer",
    11: "Normal Delivery",
    10: "Premature Delivery",
    11: "Sick Baby",
    12: "External Birth",
    13: "Home Health Transfer",
    14: "Home Health Readmission",
    15: "Same Facility Transfer",
    16: "Born Inside Hospital",
    17: "Born Outside Hospital",
    18: "Surgery Center Transfer",
    19: "Hospice Transfer",
    20: "Unknown"
}

In [148]:
admission_source["description"] = admission_source["admission_source_id"].map(admission_source_map)

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\589690558.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission_source["description"] = admission_source["admission_source_id"].map(admission_source_map)


In [149]:
admission_source = admission_source.iloc[0:20]

In [150]:
admission_source

,admission_source_id,description
0,1,Physician Referral
1,2,Clinic Referral
2,3,HMO Referral
3,4,Hospital Transfer
4,5,SNF Transfer
5,6,Healthcare Transfer
6,7,Emergency Room
7,8,Law Enforcement
8,9,Critical Hospital Transfer
9,10,Premature Delivery


In [151]:
admission_source.loc[len(admission_source)] = [21, 'Normal Delivery']

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\1782701379.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission_source.loc[len(admission_source)] = [21, 'Normal Delivery']


In [152]:
# ID	Original Description 	                           | Short Description
# ------------------------------------------------------------------------------------------------------------ 
# 1	|  Physician Referral      	                           | Physician Referral
# 2	|  Clinic Referral     	                               | Clinic Referral
# 3	| HMO Referral	                                       |  HMO Referral
# 4	|  Transfer from a hospital	                           | Hospital Transfer
# 5	| Transfer from a Skilled Nursing Facility (SNF)	   | SNF Transfer
# 6	|  Transfer from another health care facility	       | Healthcare Transfer
# 7	|  Emergency Room	                                       | Emergency Room
# 8	|  Court/Law Enforcement	                               | Law Enforcement
# 9	|  Not Available	                                       | Unknown
# 10|  Transfer from critical access hospital	           | Critical Hospital Transfer
# 11  Normal Delivery	                                   | Normal Delivery
# 12  Premature Delivery	                               | Premature Delivery
# 13  Sick Baby	                                       | Sick Baby
# 14  Extramural Birth	                               |External Birth
# 15  Not Available	                                   | Unknown
# 17  NaN                                                | Unknown
# 18  Transfer From Another Home Health Agency	       | Home Health Transfer
# 19  Readmission to Same Home Health Agency	           | Home Health Readmission
# 20  Not Mapped	                                       | Unknown
# 21  Unknown/Invalid	                                   | Unknown
# 22  Transfer from hospital inpt/same fac result in...  |Same Facility Transfer
# 23  Born inside this hospital	                       | Born Inside Hospital
# 24  Born outside this hospital	                       | Born Outside Hospital
# 25  Transfer from Ambulatory Surgery Center            |Surgery Center Transfer
# 26  Transfer from Hospice	                           | Hospice Transfer

In [153]:
admission_source.dtypes

admission_source_id     int64
description            object
dtype: object

In [154]:
admission_source["description"] = admission_source["description"].astype("string")

C:\Users\boyal\AppData\Local\Temp\ipykernel_2088\3304324445.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  admission_source["description"] = admission_source["description"].astype("string")


In [155]:
admission_source.dtypes

admission_source_id             int64
description            string[python]
dtype: object

In [156]:
# -------------------------------------------------------------------------------------------------------------------------------------------------

In [157]:
# cleaning diabities table

In [158]:
diabaties.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO


In [159]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [160]:
diabaties.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO


In [161]:
diabaties.shape

(101766, 50)

In [162]:
diabaties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   encounter_id              101766 non-null  int64 
 1   patient_nbr               101766 non-null  int64 
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64 
 7   discharge_disposition_id  101766 non-null  int64 
 8   admission_source_id       101766 non-null  int64 
 9   time_in_hospital          101766 non-null  int64 
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64 
 13  num_procedures            101766 non-null  int64 
 14  num_

In [163]:
diabaties.isna().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide 

In [164]:
# 4. LESS IMPORTANT / UNIMPORTANT COLUMNS

# These columns usually provide little business value.

# Column	                Reason
# encounter_id	            Unique visit ID only
# patient_nbr	            Patient identifier
# acetohexamide	            Rarely used medicine
# tolbutamide	            Very few records
# troglitazone	            Mostly missing/rare
# examide	                Almost all same values
# citoglipton	            Near-zero variation
# glyburide-metformin	    Rare combination
# glipizide-metformin	    Rare combination
# glimepiride-pioglitazone	Rare combination
# metformin-rosiglitazone	Rare combination
# metformin-pioglitazone	Rare combination

# These often have:

# Too many missing values
# Very low occurrence
# No meaningful impact

# You can remove many of these during cleaning.

In [165]:
diabaties.drop(columns=["encounter_id","patient_nbr", "acetohexamide", "tolbutamide","examide", "citoglipton", "glyburide-metformin", "glipizide-metformin"], inplace=True)

In [166]:
diabaties.drop(columns=["max_glu_serum", "A1Cresult"], inplace=True)

In [167]:
diabaties.shape

(101766, 40)

In [168]:
diabaties.head(20)

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,insulin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,Ch,Yes,NO
4,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,Steady,No,No,No,No,No,No,No,Steady,No,No,No,Ch,Yes,NO
5,Caucasian,Male,[50-60),?,2,1,2,3,?,?,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,Yes,>30
6,Caucasian,Male,[60-70),?,3,1,2,4,?,?,70,1,21,0,0,0,414,411,V45,7,Steady,No,No,No,Steady,No,No,No,No,No,No,No,No,Steady,No,No,No,Ch,Yes,NO
7,Caucasian,Male,[70-80),?,1,1,7,5,?,?,73,0,12,0,0,0,428,492,250,8,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,Yes,>30
8,Caucasian,Female,[80-90),?,2,1,4,13,?,?,68,2,28,0,0,0,398,427,38,8,No,No,No,No,No,Steady,No,No,No,No,No,No,No,Steady,No,No,NaN,Ch,Yes,NO
9,Caucasian,Female,[90-100),?,3,3,4,12,?,InternalMedicine,33,3,18,0,0,0,434,198,486,8,No,No,No,No,No,No,No,No,Steady,No,No,No,No,Steady,No,No,No,Ch,Yes,NO


In [169]:
diabaties.columns

Index(['race', 'gender', 'age', 'weight', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'payer_code', 'medical_specialty', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'glipizide', 'glyburide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin', 'glimepiride-pioglitazone',
       'metformin-rosiglitazone', 'metformin-pioglitazone', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')

In [170]:
diabaties["race"].unique()

array(['Caucasian', 'AfricanAmerican', '?', 'Other', 'Asian', 'Hispanic'],
      dtype=object)

In [171]:
diabaties["race"] = diabaties["race"].astype("string")

In [172]:
(diabaties["race"]=="?").sum()

np.int64(2273)

In [173]:
most_repeated = diabaties["race"].mode()[0] 
diabaties["race"] = diabaties['race'].str.replace("?",most_repeated)

In [174]:
diabaties["race"].unique()

<StringArray>
['Caucasian', 'AfricanAmerican', 'Other', 'Asian', 'Hispanic']
Length: 5, dtype: string

In [175]:
diabaties[diabaties["race"] == ""]

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,insulin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted


In [176]:
diabaties["gender"].unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [177]:
(diabaties["gender"].str.contains("Unknown")).sum()

np.int64(3)

In [178]:
diabaties[diabaties["gender"]=="Unknown/Invalid"]

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,insulin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
30506,Other,Unknown/Invalid,[70-80),?,3,1,1,1,?,Cardiology,5,5,22,0,0,0,414,411,401,4,No,No,No,No,No,Steady,No,Steady,No,No,No,No,No,No,No,No,No,Ch,Yes,NO
75551,Caucasian,Unknown/Invalid,[60-70),?,1,1,7,1,CP,?,38,1,6,0,0,0,808,873,E813,5,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
82573,Caucasian,Unknown/Invalid,[70-80),?,1,22,7,8,CP,?,59,2,21,0,0,0,850,805,808,9,Steady,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,Ch,Yes,NO


In [179]:
most_repeated_gender = diabaties["gender"].mode()[0]
diabaties["gender"] = diabaties["gender"].str.replace("Unknown/Invalid", most_repeated_gender)

In [180]:
(diabaties["gender"].str.contains("Unknown")).sum()

np.int64(0)

In [181]:
diabaties["gender"] = diabaties["gender"].astype("string")

In [182]:
diabaties["age"].unique()

array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
       '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object)

In [183]:
diabaties["age"].dtype

dtype('O')

In [184]:
diabaties["age"] = diabaties["age"].astype("string")

In [185]:
diabaties["age"] = diabaties["age"].str.replace("[","")

In [186]:
diabaties["age"] = diabaties["age"].str.replace(")","")

In [187]:
diabaties["age"].unique()

<StringArray>
[  '0-10',  '10-20',  '20-30',  '30-40',  '40-50',  '50-60',  '60-70',
  '70-80',  '80-90', '90-100']
Length: 10, dtype: string

In [188]:
diabaties["weight"].unique()

array(['?', '[75-100)', '[50-75)', '[0-25)', '[100-125)', '[25-50)',
       '[125-150)', '[175-200)', '[150-175)', '>200'], dtype=object)

In [189]:
(diabaties["weight"] == "?").sum()

np.int64(98569)

In [190]:
diabaties.drop(columns="weight", inplace=True)

In [191]:
diabaties["admission_type_id"].unique()

array([6, 1, 2, 3, 4, 5, 8, 7])

In [192]:
admission

,admission_type_id,description
0,1,Emergency
1,2,Urgent
2,3,Elective
3,4,Newborn
4,5,Unknown
5,5,Unknown
6,7,Trauma Center
7,5,Unknown


In [193]:
diabaties["admission_type_id"] = diabaties["admission_type_id"].replace(6, 5)
diabaties["admission_type_id"] = diabaties["admission_type_id"].replace(8, 5)

In [194]:
diabaties["admission_type_id"].unique()

array([5, 1, 2, 3, 4, 7])

In [195]:
diabaties["discharge_disposition_id"].unique()

array([25,  1,  3,  6,  2,  5, 11,  7, 10,  4, 14, 18,  8, 13, 12, 16, 17,
       22, 23,  9, 20, 15, 24, 28, 19, 27])

In [196]:
diabaties["discharge_disposition_id"].unique()

array([25,  1,  3,  6,  2,  5, 11,  7, 10,  4, 14, 18,  8, 13, 12, 16, 17,
       22, 23,  9, 20, 15, 24, 28, 19, 27])

In [197]:
first = 6, 8
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(first, 1)

In [198]:
second = 5, 23, 27, 29, 30
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(second, 2)

In [199]:
third =  4, 22, 24
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(third, 3)

In [200]:
fourth =  13, 14
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(fourth, 4)

In [201]:
fifth = 11, 19, 20, 21
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(fifth, 5)

In [202]:
sixth =  12, 16, 17
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(sixth, 6)

In [203]:

diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(7,8)
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(28, 7)

In [204]:
others = 18, 25, 26
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(others, 13)

In [205]:
diabaties["discharge_disposition_id"] = diabaties["discharge_disposition_id"].replace(15, 11)

In [206]:
description_map = {
    1: "Home",
    2: "Hospital Transfer",
    3: "Nursing/Rehab Care",
    4: "Hospice Care",
    5: "Expired",
    6: "Outpatient Services",
    7: "Psychiatric Care",
    8: "Left Against Advice",
    9: "Inpatient Admission",
    10: "Neonatal Care",
    11: "Swing Bed",
    12: "Outpatient Return"
}

In [207]:
# Category	                IDs Included
# Home	                    1, 6, 8
# Hospital Transfer	        2, 5, 23, 27, 29, 30
# Nursing/Rehab Care	    3, 4, 22, 24
# Hospice Care            	13, 14
# Expired	                11, 19, 20, 21
# Outpatient Services	    12, 16, 17
# Psychiatric Care	        28
# Left Against Advice     	7
# Other/Unknown	            18, 25, 26
# Inpatient Admission	    9
# Neonatal Care	            10
# Swing Bed	                15

In [208]:
discharge

,discharge_disposition_id,description
0,1,Home
1,2,Hospital Transfer
2,3,Nursing/Rehab Care
3,4,Hospice Care
4,5,Expired
5,6,Outpatient Services
6,7,Psychiatric Care
7,8,Left Against Advice
8,9,Inpatient Admission
9,10,Neonatal Care


In [209]:
diabaties["discharge_disposition_id"].unique()

array([13,  1,  3,  2,  5,  8, 10,  4,  6,  9, 11,  7])

In [210]:
diabaties["admission_source_id"].unique()

array([ 1,  7,  2,  4,  5,  6, 20,  3, 17,  8,  9, 14, 10, 22, 11, 25, 13])

In [211]:
admission_source

,admission_source_id,description
0,1,Physician Referral
1,2,Clinic Referral
2,3,HMO Referral
3,4,Hospital Transfer
4,5,SNF Transfer
5,6,Healthcare Transfer
6,7,Emergency Room
7,8,Law Enforcement
8,9,Critical Hospital Transfer
9,10,Premature Delivery


In [212]:
unknown = 9, 15, 17, 20, 21
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(unknown, 20)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(10, 9)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(12, 10)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(11, 21)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(13, 11)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(14, 12)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(18, 13)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(19, 14)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(22, 15)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(23, 16)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(24, 17)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(25, 18)
diabaties["admission_source_id"] = diabaties["admission_source_id"].replace(14, 19)

In [213]:
# Recommended Short Descriptions
#---------------------------------------------------------------------------------------------
# ID	Original Description	                                Short Description
#----------------------------------------------------------------------------------------------
# 1	    Physician Referral	                                    Physician Referral
# 2 	Clinic Referral	                                        Clinic Referral
# 3	    HMO Referral	                                        HMO Referral
# 4	    Transfer from a hospital	                            Hospital Transfer
# 5	    Transfer from a Skilled Nursing Facility (SNF)	        SNF Transfer
# 6	    Transfer from another health care facility	            ealthcare Transfer
# 7	    Emergency Room	                                        Emergency Room
# 8	    Court/Law Enforcement	                                Law Enforcement
# 9	    Not Available	                                        Unknown
# 10    Transfer from critical access hospital	                Critical Hospital Transfer
# 11	Normal Delivery	                                        Normal Delivery
# 12	Premature Delivery	                                    Premature Delivery
# 13	Sick Baby	                                            Sick Baby
# 14	Extramural Birth	                                    External Birth
# 15	Not Available	                                        Unknown
# 17	NaN	                                                    Unknown
# 18	Transfer From Another Home Health Agency	            Home Health Transfer
# 19	Readmission to Same Home Health Agency	                Home Health Readmission
# 20	Not Mapped	                                            Unknown
# 21	Unknown/Invalid	                                        Unknown
# 22    Transfer from hospital inpt/same fac result in...	    Same Facility Transfer
# 23	Born inside this hospital	                            Born Inside Hospital
# 24	Born outside this hospital	                            Born Outside Hospital
# 25	Transfer from Ambulatory Surgery Center	                Surgery Center Transfer
# 26	Transfer from Hospice	                                Hospice Transfer

In [214]:
# 	admission_source_id	description
# 0	1	Physician Referral
# 1	2	Clinic Referral
# 2	3	HMO Referral
# 3	4	Transfer from a hospital
# 4	5	Transfer from a Skilled Nursing Facility (SNF)
# 5	6	Transfer from another health care facility
# 6	7	Emergency Room
# 7	8	Court/Law Enforcement
# 8	9	Not Available
# 9	10	Transfer from critial access hospital
# 10	12	Premature Delivery
# 12	11	Normal Delivery
# 11	13	Sick Baby
# 13	15	Not Available
# 15	14	Extramural Birth
# 14	17	Transfer From Another Home Health Agency
# 17	1	NaN
# 16	189	Readmission to Same Home Health Agency
# 18	20	Not Mapped
# 19	21	Unknown/Invalid
# 20	22	Transfer from hospital inpt/same fac reslt in a sep claim
# 21	23	Born inside this hospital
# 22	24	Born outside this hospital
# 23	25	Transfer from Ambulatory Surgery Center
# 24	26	Transfer from Hospice


In [215]:
diabaties["admission_source_id"].unique()

array([ 1,  7,  2,  4,  5,  6, 20,  3,  8, 12,  9, 15, 21, 18, 11])

In [216]:
diabaties.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,insulin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,0-10,5,13,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,Caucasian,Female,10-20,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,20-30,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,30-40,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,Ch,Yes,NO
4,Caucasian,Male,40-50,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,Steady,No,No,No,No,No,No,No,Steady,No,No,No,Ch,Yes,NO


In [217]:
diabaties["time_in_hospital"].unique()

array([ 1,  3,  2,  4,  5, 13, 12,  9,  7, 10,  6, 11,  8, 14])

In [218]:
diabaties["payer_code"].unique()

array(['?', 'MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM',
       'CH', 'PO', 'WC', 'OT', 'OG', 'MP', 'FR'], dtype=object)

In [219]:
(diabaties["payer_code"] == "?").sum()

np.int64(40256)

In [ ]:
diabaties["payer_code"].unique()

array(['?', 'MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM',
       'CH', 'PO', 'WC', 'OT', 'OG', 'MP', 'FR'], dtype=object)

In [225]:
mr_payer_code = diabaties["payer_code"].value_counts().index[1]
print(mr_payer_code)

MC


In [228]:
diabaties["payer_code"] = diabaties["payer_code"].astype("string")
diabaties["payer_code"] = diabaties["payer_code"].str.replace("?",mr_payer_code)

In [229]:
diabaties["payer_code"].unique()

<StringArray>
['MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM', 'CH', 'PO', 'WC',
 'OT', 'OG', 'MP', 'FR']
Length: 17, dtype: string

In [ ]:
diabaties["medical_specialty"].unique()

array(['Pediatrics-Endocrinology', '?', 'InternalMedicine',
       'Family/GeneralPractice', 'Cardiology', 'Surgery-General',
       'Orthopedics', 'Gastroenterology',
       'Surgery-Cardiovascular/Thoracic', 'Nephrology',
       'Orthopedics-Reconstructive', 'Psychiatry', 'Emergency/Trauma',
       'Pulmonology', 'Surgery-Neuro',
       'Obsterics&Gynecology-GynecologicOnco', 'ObstetricsandGynecology',
       'Pediatrics', 'Hematology/Oncology', 'Otolaryngology',
       'Surgery-Colon&Rectal', 'Pediatrics-CriticalCare', 'Endocrinology',
       'Urology', 'Psychiatry-Child/Adolescent', 'Pediatrics-Pulmonology',
       'Neurology', 'Anesthesiology-Pediatric', 'Radiology',
       'Pediatrics-Hematology-Oncology', 'Psychology', 'Podiatry',
       'Gynecology', 'Oncology', 'Pediatrics-Neurology',
       'Surgery-Plastic', 'Surgery-Thoracic',
       'Surgery-PlasticwithinHeadandNeck', 'Ophthalmology',
       'Surgery-Pediatric', 'Pediatrics-EmergencyMedicine',
       'PhysicalMedicineandRe

In [232]:
diabaties["medical_specialty"].value_counts()

medical_specialty
?                                       49949
InternalMedicine                        14635
Emergency/Trauma                         7565
Family/GeneralPractice                   7440
Cardiology                               5352
Surgery-General                          3099
Nephrology                               1613
Orthopedics                              1400
Orthopedics-Reconstructive               1233
Radiologist                              1140
Pulmonology                               871
Psychiatry                                854
Urology                                   685
ObstetricsandGynecology                   671
Surgery-Cardiovascular/Thoracic           652
Gastroenterology                          564
Surgery-Vascular                          533
Surgery-Neuro                             468
PhysicalMedicineandRehabilitation         391
Oncology                                  348
Pediatrics                                254
Hematology/Oncol

In [ ]:

diabaties.loc[
    diabaties["medical_specialty"].isin(["Speech","SportsMedicine","Perinatology", "Neurophysiology", "Psychiatry-Addictive", "Pediatrics-InfectiousDiseases", "Proctology","Dermatology"
    "Pediatrics-EmergencyMedicine", "Pediatrics-AllergyandImmunology","Resident","Surgery-PlasticwithinHeadandNeck", "Pediatrics-Hematology-Oncology", "Dentistry","Pediatrics-EmergencyMedicine"
      ]),
    "medical_specialty"
] = "Others"

In [250]:
specialty_count = diabaties["medical_specialty"].value_counts()
rare_specalty = specialty_count[specialty_count< 100].index

diabaties.loc[
    diabaties["medical_specialty"].isin(rare_specalty),
    "medical_specialty"
] = "Others"

In [251]:
diabaties["medical_specialty"].value_counts()

medical_specialty
?                                    49949
InternalMedicine                     14635
Emergency/Trauma                      7565
Family/GeneralPractice                7440
Cardiology                            5352
Surgery-General                       3099
Nephrology                            1613
Orthopedics                           1400
Orthopedics-Reconstructive            1233
Radiologist                           1140
Others                                 925
Pulmonology                            871
Psychiatry                             854
Urology                                685
ObstetricsandGynecology                671
Surgery-Cardiovascular/Thoracic        652
Gastroenterology                       564
Surgery-Vascular                       533
Surgery-Neuro                          468
PhysicalMedicineandRehabilitation      391
Oncology                               348
Pediatrics                             254
Hematology/Oncology                 

In [252]:
diabaties["medical_specialty"] = diabaties["medical_specialty"].replace("?", "Unknown")

In [253]:
diabaties["medical_specialty"].unique()

array(['Pediatrics-Endocrinology', 'Unknown', 'InternalMedicine',
       'Family/GeneralPractice', 'Cardiology', 'Surgery-General',
       'Orthopedics', 'Gastroenterology',
       'Surgery-Cardiovascular/Thoracic', 'Nephrology',
       'Orthopedics-Reconstructive', 'Psychiatry', 'Emergency/Trauma',
       'Pulmonology', 'Surgery-Neuro', 'Others',
       'ObstetricsandGynecology', 'Pediatrics', 'Hematology/Oncology',
       'Otolaryngology', 'Endocrinology', 'Urology', 'Neurology',
       'Psychology', 'Podiatry', 'Oncology', 'Surgery-Thoracic',
       'PhysicalMedicineandRehabilitation', 'Surgery-Vascular',
       'Radiologist'], dtype=object)

In [255]:
diabaties["num_lab_procedures"].unique()

array([ 41,  59,  11,  44,  51,  31,  70,  73,  68,  33,  47,  62,  60,
        55,  49,  75,  45,  29,  35,  42,  66,  36,  19,  64,  25,  53,
        52,  87,  27,  37,  46,  28,  48,  72,  10,   2,  65,  67,  40,
        54,  58,  57,  43,  32,  83,  34,  39,  69,  38,  56,  22,  96,
        78,  61,  88,  50,   1,  18,  82,   9,  63,  24,  71,  77,  81,
        76,  90,  93,   3, 103,  13,  80,  85,  16,  15,  12,  30,  23,
        17,  21,  79,  26,   5,  95,  97,  84,  14,  74, 105,  86,  98,
        20,   6,  94,   8, 102, 100,   7,  89,  91,  92,   4, 101,  99,
       114, 113, 111, 129, 107, 108, 106, 104, 109, 120, 132, 121, 126,
       118])

In [256]:
diabaties["num_procedures"].unique()

array([0, 5, 1, 6, 2, 3, 4])

In [257]:
diabaties["num_medications"].unique()

array([ 1, 18, 13, 16,  8, 21, 12, 28, 17, 11, 15, 31,  2, 23, 19,  7, 20,
       14, 10, 22,  9, 27, 25,  4, 32,  6, 30, 26, 24, 33,  5, 39,  3, 29,
       61, 40, 46, 41, 36, 34, 35, 50, 43, 42, 37, 51, 38, 45, 54, 52, 49,
       62, 55, 47, 44, 53, 48, 57, 59, 56, 60, 63, 58, 70, 67, 64, 69, 65,
       68, 66, 81, 79, 75, 72, 74])

In [258]:
diabaties["number_outpatient"].unique()

array([ 0,  2,  1,  5,  7,  9,  3,  8,  4, 12, 11,  6, 20, 15, 10, 13, 14,
       16, 21, 35, 17, 29, 36, 18, 19, 27, 22, 24, 42, 39, 34, 26, 33, 25,
       23, 28, 37, 38, 40])

In [259]:
diabaties["number_emergency"].unique()

array([ 0,  1,  2,  4,  3,  9,  5,  7,  6,  8, 22, 25, 10, 13, 42, 16, 11,
       28, 15, 14, 18, 12, 21, 20, 19, 46, 76, 37, 64, 63, 54, 24, 29])

In [260]:
diabaties["number_inpatient"].unique()

array([ 0,  1,  2,  3,  6,  5,  4,  7,  8,  9, 15, 10, 11, 14, 12, 13, 17,
       16, 21, 18, 19])

In [261]:
diabaties["diag_1"].unique()

array(['250.83', '276', '648', '8', '197', '414', '428', '398', '434',
       '250.7', '157', '518', '999', '410', '682', '402', '737', '572',
       'V57', '189', '786', '427', '996', '277', '584', '462', '473',
       '411', '174', '486', '998', '511', '432', '626', '295', '196',
       '250.6', '618', '182', '845', '423', '808', '250.4', '722', '403',
       '250.11', '784', '707', '440', '151', '715', '997', '198', '564',
       '812', '38', '590', '556', '578', '250.32', '433', 'V58', '569',
       '185', '536', '255', '250.13', '599', '558', '574', '491', '560',
       '244', '250.03', '577', '730', '188', '824', '250.8', '332', '562',
       '291', '296', '510', '401', '263', '438', '70', '250.02', '493',
       '642', '625', '571', '738', '593', '250.42', '807', '456', '446',
       '575', '250.41', '820', '515', '780', '250.22', '995', '235',
       '250.82', '721', '787', '162', '724', '282', '514', 'V55', '281',
       '250.33', '530', '466', '435', '250.12', 'V53', '789', '

In [264]:
def categorize_diagnosis(code):

    if code == "?":
        return "Unknown"

    code = str(code)

    if code.startswith("V"):
        return "Supplementary"

    elif code.startswith("E"):
        return "External Causes"

    try:
        code = float(code)

        if 1 <= code <= 139:
            return "Infectious Diseases"

        elif 140 <= code <= 239:
            return "Neoplasms"

        elif 240 <= code <= 279:
            return "Endocrine/Metabolic"

        elif 280 <= code <= 289:
            return "Blood Diseases"

        elif 290 <= code <= 319:
            return "Mental Disorders"

        elif 320 <= code <= 389:
            return "Nervous System"

        elif 390 <= code <= 459:
            return "Circulatory"

        elif 460 <= code <= 519:
            return "Respiratory"

        elif 520 <= code <= 579:
            return "Digestive"

        elif 580 <= code <= 629:
            return "Genitourinary"

        elif 630 <= code <= 679:
            return "Pregnancy"

        elif 680 <= code <= 709:
            return "Skin Diseases"

        elif 710 <= code <= 739:
            return "Musculoskeletal"

        elif 740 <= code <= 759:
            return "Congenital"

        elif 760 <= code <= 779:
            return "Perinatal"

        elif 780 <= code <= 799:
            return "Symptoms"

        elif 800 <= code <= 999:
            return "Injury/Poisoning"

        else:
            return "Other"

    except:
        return "Other"

In [265]:
diabaties["diag_1_category"] = diabaties["diag_1"].apply(categorize_diagnosis)

diabaties["diag_2_category"] = diabaties["diag_2"].apply(categorize_diagnosis)

diabaties["diag_3_category"] = diabaties["diag_3"].apply(categorize_diagnosis)

In [267]:
diabaties.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,insulin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,diag_1_category,diag_2_category,diag_3_category
0,Caucasian,Female,0-10,5,13,1,1,MC,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Endocrine/Metabolic,Unknown,Unknown
1,Caucasian,Female,10-20,1,1,7,3,MC,Unknown,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,Ch,Yes,>30,Endocrine/Metabolic,Endocrine/Metabolic,Endocrine/Metabolic
2,AfricanAmerican,Female,20-30,1,1,7,2,MC,Unknown,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,Pregnancy,Endocrine/Metabolic,Supplementary
3,Caucasian,Male,30-40,1,1,7,2,MC,Unknown,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,Ch,Yes,NO,Infectious Diseases,Endocrine/Metabolic,Circulatory
4,Caucasian,Male,40-50,1,1,7,1,MC,Unknown,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,Steady,No,No,No,No,No,No,No,Steady,No,No,No,Ch,Yes,NO,Neoplasms,Neoplasms,Endocrine/Metabolic


In [268]:
diabaties["number_diagnoses"].unique()

array([ 1,  9,  6,  7,  5,  8,  3,  4,  2, 16, 12, 13, 15, 10, 11, 14])

In [270]:
diabaties["metformin"].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [271]:
diabaties["repaglinide"].unique()

array(['No', 'Up', 'Steady', 'Down'], dtype=object)

In [273]:
diabaties["nateglinide"].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [274]:
diabaties["chlorpropamide"].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [275]:
diabaties["glimepiride"].unique()

array(['No', 'Steady', 'Down', 'Up'], dtype=object)

In [276]:
diabaties["glipizide"].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [278]:
diabaties["glyburide"].unique()

array(['No', 'Steady', 'Up', 'Down'], dtype=object)

In [279]:
diabaties["change"].unique()

array(['No', 'Ch'], dtype=object)

In [280]:
diabaties.loc[
    diabaties["change"]=="Ch",
    "change"
] = "Yes"

In [281]:
diabaties["change"].unique()

array(['No', 'Yes'], dtype=object)

In [282]:
diabaties["readmitted"].unique()

array(['NO', '>30', '<30'], dtype=object)

In [283]:
categorical_cols = [
    "race",
    "gender",
    "age",
    "medical_specialty",
    "diag_1_category",
    "diag_2_category",
    "diag_3_category",
    "readmitted"
]

In [284]:
for col in categorical_cols:
    diabaties[col] = diabaties[col].astype("category")

In [285]:
diabaties.to_csv(
    r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\02_Cleaned_data\cleaned_diabaties_table.csv",
    index=False
)

admission.to_csv(
    r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\02_Cleaned_data\cleaned_admission_table.csv",
    index=False
)
admission_source.to_csv(
    r"C:\Users\boyal\OneDrive\End-to-End-Data-Analytics-Projects\03_Medical_Analysis\01_Data\02_Cleaned_data\cleaned_admission_source_table.csv",
    index=False
)

In [287]:
diabaties["age"].unique()

['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90', '90-100']
Categories (10, string): [0-10, 10-20, 20-30, 30-40, ..., 60-70, 70-80, 80-90, 90-100]

In [288]:
diabaties.isna().sum()

race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
glipizide                   0
glyburide                   0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
insulin                     0
glimepirid

In [291]:
(diabaties["metformin-pioglitazone"] == " ").sum()

np.int64(0)